/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgVariableBindingManager.java
 *
 * Created on Apr 10, 2009, 9:07:10 AM
 */
package com.advoss.network.analyzer.gui;

import com.advoss.network.analyzer.Constants;
import com.advoss.util.SwingUtilities;
import javax.swing.DefaultComboBoxModel;
import org.ict.oamp.service.client.TrapBindingDefinition;
import org.ict.oamp.service.client.VariableType;

/**
 *
 * @author Alam Sher
 */
public class DlgVariableBindingManager extends javax.swing.JDialog {

    private TrapBindingDefinition bindingDefinition = null;
    private int action = Constants.ACTION_ADD;
    
    private DefaultComboBoxModel dataTypesModel = new DefaultComboBoxModel();

    /** Creates new form DlgVariableBindingManager */
    public DlgVariableBindingManager(java.awt.Frame parent, boolean modal, int action, TrapBindingDefinition bindingDefinition) {
        super(parent, modal);
        this.action = action;
        this.bindingDefinition = bindingDefinition;
        initComponents();
        customize();
    }

    private void customize() {
        dataTypesModel.addElement(VariableType._UNKNOWN);
        dataTypesModel.addElement(VariableType._NULL);
        dataTypesModel.addElement(VariableType._INTEGER32);
        dataTypesModel.addElement(VariableType._STRING);
        dataTypesModel.addElement(VariableType._COUNTER32);
        dataTypesModel.addElement(VariableType._COUNTER64);
        dataTypesModel.addElement(VariableType._GUAGE32);
        dataTypesModel.addElement(VariableType._TIMETICKS);
        dataTypesModel.addElement(VariableType._UINTEGER32);
        dataTypesModel.addElement(VariableType._OPAQUE);
        dataTypesModel.addElement(VariableType._OID);
        if(action == Constants.ACTION_EDIT) {
            loadData();
        }
    }

    private void loadData() {
        if(bindingDefinition != null) {
            txtOID.setText(bindingDefinition.getVariableOid().trim());
            txtVariableName.setText(bindingDefinition.getVariableName().trim());
            txtDescription.setText(bindingDefinition.getBindingDescription().trim());
            try {
                cmbDataType.setSelectedItem(bindingDefinition.getVariableType().toString());
            } catch(Exception ex){
            }
        }
    }

    public boolean validateFields() {
        if(txtOID.getText().trim().equalsIgnoreCase("")) {
            SwingUtilities.showErrorMessage("Variable OID can't be left empty");
            return false;
        } else if (txtVariableName.getText().trim().equalsIgnoreCase("")) {
            SwingUtilities.showErrorMessage("Variable Name can't be left empty");
            return false;
        }
        return true;
    }

    public TrapBindingDefinition getBindingDefinition() {
        return this.bindingDefinition;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlMain = new javax.swing.JPanel();
        lblOID = new javax.swing.JLabel();
        txtOID = new javax.swing.JTextField();
        lblDataType = new javax.swing.JLabel();
        cmbDataType = new javax.swing.JComboBox();
        pnlDescription = new javax.swing.JPanel();
        scrollPaneDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblVariableName = new javax.swing.JLabel();
        txtVariableName = new javax.swing.JTextField();
        pnlControls = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setLayout(new java.awt.GridBagLayout());

        lblOID.setText("Binding OID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(lblOID, gridBagConstraints);

        txtOID.setColumns(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(txtOID, gridBagConstraints);

        lblDataType.setText("Binding Data Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(lblDataType, gridBagConstraints);

        cmbDataType.setModel(dataTypesModel);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(cmbDataType, gridBagConstraints);

        pnlDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Custom Description"));
        pnlDescription.setLayout(new java.awt.BorderLayout());

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        scrollPaneDescription.setViewportView(txtDescription);

        pnlDescription.add(scrollPaneDescription, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(pnlDescription, gridBagConstraints);

        lblVariableName.setText("Variable Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(lblVariableName, gridBagConstraints);

        txtVariableName.setColumns(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlMain.add(txtVariableName, gridBagConstraints);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlControls.add(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlControls.add(btnCancel);

        getContentPane().add(pnlControls, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(validateFields()) {
            if(action == Constants.ACTION_ADD) {
                bindingDefinition = new TrapBindingDefinition();
                bindingDefinition.setVariableOid(txtOID.getText().trim());
                bindingDefinition.setVariableName(txtVariableName.getText().trim());
                bindingDefinition.setVariableType(VariableType.fromValue(cmbDataType.getSelectedItem().toString()));
                bindingDefinition.setBindingDescription(txtDescription.getText().trim());
                this.dispose();
            } else {
                bindingDefinition.setVariableOid(txtOID.getText().trim());
                bindingDefinition.setVariableName(txtVariableName.getText().trim());
                bindingDefinition.setVariableType(VariableType.fromValue(cmbDataType.getSelectedItem().toString()));
                bindingDefinition.setBindingDescription(txtDescription.getText().trim());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbDataType;
    private javax.swing.JLabel lblDataType;
    private javax.swing.JLabel lblOID;
    private javax.swing.JLabel lblVariableName;
    private javax.swing.JPanel pnlControls;
    private javax.swing.JPanel pnlDescription;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane scrollPaneDescription;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtOID;
    private javax.swing.JTextField txtVariableName;
    // End of variables declaration//GEN-END:variables
}
